### ISSUE TITLE
Question about how this is done

### ISSUE THREAD

**Issue by toxicrecker** [Alkaid-Benetnash/EmuBTHID#10]
How did you figure out all the mapping and the keyboard and mouse state bytearrays? im asking this as im trying to do something similar with an xbox360 controller

**Comment by Alkaid-Benetnash** [comment]
Hi, keycode are tracked in `keycode.txt`, where you can find the description of the data source at the very beginning.
In short, the mapping is taken from the USB HID usage reference (e.g., [here is a link](https://www.usb.org/sites/default/files/hut1_3_0.pdf)).
There are dedicated section for gaming control in these kind of documentations.
Good luck!
