### ISSUE TITLE
How to move cursor to exact coordinates

### ISSUE THREAD

**Issue by hungtooc** [Alkaid-Benetnash/EmuBTHID#4]
Hi, thanks for great source code.
as i know we can move cursor to new location by changing X and Y when e.type == X.MotionNotify
```
mouse_state = bytearray([
            0xA1,
            0x02,  # Report ID
            0x00,  # mouse button, in this byte XXXXX(button2)(button1)(button0)
            0x00,  # X displacement
            0x00,  # Y displacement
        ])
```
where `x_coord = old_x_coord + X` and `y_coord = old_y_coord + Y` on client device.

How to move cursor to exact coordinates when server doesn't know current cursor coordinates?

**Comment by Alkaid-Benetnash** [comment]
Hi, I do not know how to do that.

You have to go through the Bluetooth HID profile documentation to find whether there exists a special "report" that can control the absolute coordinates. My guess is that the HID for touchscreen-like devices (if there is one) is what you want to emulate.
