### ISSUE TITLE
'bluetoothd -P input' not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by guliteb** [Alkaid-Benetnash/EmuBTHID#9]
I  am using Ubuntu 22.04. BlueZ is native installed. When I run 'sudo bluetoothd -P input', it shows ''D-Bus setup failed: Name already in use'. And then running 'sudo python3 main.py' resulted in 'Address already in use'.

How should I resolve this failure?

Thanks.

**Comment by Alkaid-Benetnash** [comment]
Can you double check whether the Ubuntu has also started another bluetoothd?
Like normally many distros that I have seen will have a `systemctl status bluetooth` service running in the background by default. If you found one, you have to stop it or change its startup options.

**Comment by guliteb** [comment]
Thanks. It works after I run `systemctl stop bluetooth` and manually start `sudo bluetoothd -P input`.
